name: ci/cd pipeline actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dockerdemo
          path: ${{ github.workspace }}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dockerdemo
      - name: Deploying to Azure
        uses: azure/webapp-deploy@v2
        with:
          app-name: PRACTISEAPP1
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: '*.jar'
